### ISSUE TITLE
Update for sensor.last_successful_authentication fails

### ISSUE THREAD

**Issue by tjorim** [custom-components/sensor.authenticated#24]
**Version of the cusom_component**

sensor.authenticated 0.1.0
supervisor 125
homeassistant 0.75.3

**Describe the bug**
A dev info log full of errors: `custom_components/sensor/authenticated.py (ERROR)`

**log**

```
Update for sensor.last_successful_authentication fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 322, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/authenticated.py", line 174, in update
    if checkpath.exists():
  File "/config/custom_components/sensor/authenticated.py", line 104, in new_ip
    self.write_file(ip_address, access_time, hostname, geo_country, geo_region, geo_city)
  File "/config/custom_components/sensor/authenticated.py", line 144, in write_file
    city=city
TypeError: 'NoneType' object does not support item assignment
```

**Comment by ludeeus** [comment]
demn...
I was hoping I was the only one getting that :/
Will look in to it ;)

**Comment by ludeeus** [comment]
@tjorim I have updated this to v0.2.0 can you try that and see if it helps?
I have not seen it after that upgrade (yet)

**Comment by tjorim** [comment]
I haven't updated yet but haven't seen it again since a restart.
Seems very sporadic but once it started, it keeps doing it.
I will update and report back if it happens again.
