### ISSUE TITLE
Error while setting up platform authenticated

### ISSUE THREAD

**Issue by tjorim** [custom-components/sensor.authenticated#26]
**Version of the cusom_component**
sensor.authenticated 0.2.0
supervisor 125
homeassistant 0.75.3

**Describe the bug**
After updating the sensor from 0.1.0 to 0.2.0 because of another bug I encountered (#24),
I enabled the component again and rebooted, after the reboot I got the following error:
`Error while setting up platform authenticated`. I tried to reboot a second time, same thing happened.

Also I'm now noticing the error `Login attempt or request with invalid authentication from 127.0.0.1`
which I think is new since updating this component. Might be unrelated but just wanted to mention.
For your info, I'm currently using the new auth_providers, legacy_api_password still enabled.

**log**
Log Details (ERROR)
Sat Aug 11 2018 20:26:40 GMT+0200 (Midden-Europese zomertijd)

```
Error while setting up platform authenticated
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/authenticated.py", line 54, in setup_platform
    add_devices([Authenticated(hass, notify, log, out, exclude)])
  File "/config/custom_components/sensor/authenticated.py", line 75, in __init__
    self.initial_run()
  File "/config/custom_components/sensor/authenticated.py", line 82, in initial_run
    for ip_address in file_content:
TypeError: 'NoneType' object is not iterable
```

**Comment by ludeeus** [comment]
is your .ip_authenticated.yaml file empty?
if so delete it
