### ISSUE TITLE
Failed to boot / python error on logs

### ISSUE THREAD

**Issue by axerontios** [custom-components/sensor.authenticated#33]
**Version of the custom_component**
latest available 

HA Installed Version
10 minutes ago
0.87.1
root@xxxxxx:/usr/share/hassio/homeassistant/custom_components/authenticated# pwd
/usr/share/hassio/homeassistant/custom_components/authenticated
root@xxxxxx:/usr/share/hassio/homeassistant/custom_components/authenticated# ls
__pycache__  sensor.py

--on the sensor folder.
--CONFIG FILE
sensor: !include_dir_merge_list SensorS
--SENSOR YAML FILE
- platform: authenticated
  enable_notification: true

**Describe the bug**

**log**

```
2019-02-17 22:09:59 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform authenticated
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/authenticated/sensor.py", line 59, in setup_platform
    hass.services.call('logger', 'set_level', logs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1074, in call
    self._hass.loop
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1107, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: (ServiceNotFound(...), 'Service logger.set_level not found')
```

**Comment by ludeeus** [comment]
You need to enable `logger:` in your configuration.yaml

**Comment by axerontios** [comment]
@ludeeus you are a rock star, that did the trick, if only i was more careful reading those logs, thanks mate !
